### ISSUE TITLE
Update to 0.9.5 and possible startup without having an association.sqlite?

### ISSUE THREAD

**Issue by gromain** [ajanvier/docker-garradin#1]
Hi there!

I wanted to use this image for my association and was wondering if you could update it to v0.9.5 .

Also, is there a way for first time users to startup without having a populated association.sqlite? Maybe creating an empty database and starting with that?

Cheers,

Romain

**Comment by SamuelAllain** [comment]
Thanks @ajanvier for this work ! Exact same request as @gromain : it'd be great to either have a association.sqlite example or a way to start a new one.

**Comment by SamuelAllain** [comment]
@gromain this is how I did :

1. launch a container without any volume : `sudo docker run -d --name gara -p 80:80 ajanvier/garradin`
2. on your browser, go to [localhost:80](localhost:80), fill all the required infos
3. copy the sqlite database (dirty way but I don't know how to do in a cleaner way) : `sudo docker cp gara:/src/association.sqlite ./`
4. stop the container : `sudo docker rm -f gara`
5. launch a new container with the volume so that you keep the changes : `sudo docker run -d --name gara -p 80:80  -v ABSOLUTE_PATH/association.sqlite:/src/association.sqlite ajanvier/garradin`. Beware the command suggested on the readme did not work for me, docker asked for the absolute path
(EDIT : too dirty ! the database is read-only then)

@ajanvier would you have a better idea for the container to work with or without a association.sqlite ?

**Comment by SamuelAllain** [comment]
Please forget my weird steps. The best is to use a real volume. With a real volume, you can start the database from scratch and you can use the same command to keep the changes. Plus it solves the "absolute path" requirement. And it is so much simpler :

```
sudo docker run -d --name gara -p 80:80 -v garradin-src:/src/ ajanvier/garradin
```
@ajanvier, would you consider putting that command ?

**Comment by SamuelAllain** [comment]
@gromain I built [a new image](https://hub.docker.com/r/samuelallain/garradin) with Garradin 1.1.25 (Alpine 3.1.16, PHP 8.1 and Nginx 1.22.0)

**Comment by ajanvier** [comment]
Hello,

Well, I completely missed out on this issue, sorry about that.

As I haven't been using garradin for more than two years so I've ceased supporting this image.
Thus, I'll mark it as unmaintained and redirect to @SamuelAllain's work (thanks to him).

Thanks to everyone who's been using this image and good luck to @SamuelAllain for maintaining his own !
